export const jobs = [
  {
    title: "Test",
    applicants: 2,
    country: "France",
    dutyStation: "Paris",
    type: "Full-time",
    status: "International consultant",
    languages: ["English", "French"],
    openingDate: "10 Febuary 2023",
    closingDate: "10 March 2023",
    Organization: "IMMAP",
    creator: {
      name: "(Murhula Metre)",
      email: "asyaifa@immap.org",
    },
  },
  {
    title: "Test 2",
    applicants: 6,
    country: "Brazil",
    dutyStation: "Rio de janeiro",
    type: "Full-time",
    status: "International consultant",
    languages: ["English", "Spanish"],
    openingDate: "5 Febuary 2023",
    closingDate: "3 March 2023",
    Organization: "IMMAP",
    creator: {
      name: "(Murhula Metre)",
      email: "asyaifa@immap.org",
    },
  },
  {
    title: "Test 3",
    applicants: 2,
    country: "France",
    dutyStation: "Marseille",
    type: "Part-time",
    status: "International consultant",
    languages: ["English", "French"],
    openingDate: "1 Febuary 2023",
    closingDate: "28 Fevrier 2023",
    Organization: "IMMAP",
    creator: {
      name: "(Murhula Metre)",
      email: "asyaifa@immap.org",
    },
  },
];

export const job = {
  title: "Test",
  applicants: 2,
  country: "France",
  dutyStation: "Paris",
  type: "Full-time",
  status: "International consultant",
  languages: ["English", "French"],
  openingDate: "10 Febuary 2023",
  closingDate: "10 March 2023",
  Organization: "IMMAP",
  creator: {
    name: "(Murhula Metre)",
    email: "asyaifa@immap.org",
  },
};
